### ISSUE TITLE
T1w registration with --longitudinal

### ISSUE THREAD

**Issue by araikes** [PennBBL/qsiprep#104]
Ran into this issue on the same subject with `0.7.2` (deobliqued) and `0.8.0RC2` (non-deobliqued):

A similar error was reported in an early version of fMRIPrep and subsequently fixed (https://github.com/poldracklab/fmriprep/pull/771).

```
Node: qsiprep_wf.single_subject_BLMTBI118_wf.anat_preproc_wf.anat_template_wf.t1_merge
Working directory: /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/t1_merge

Node inputs:

args = <undefined>
auto_detect_sensitivity = True
average_metric = <undefined>
environ = {'SUBJECTS_DIR': '/opt/freesurfer/subjects', 'OMP_NUM_THREADS': '1'}
fixed_timepoint = False
in_files = ['/data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-BLMTBI118_ses-bline_run-001_T1w_corrected.nii.gz', '/data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-BLMTBI118_ses-ptx_run-001_T1w_lps_corrected.nii.gz']
in_intensity_scales = <undefined>
initial_timepoint = 1
initial_transforms = <undefined>
intensity_scaling = True
no_iteration = False
num_threads = 2
out_file = sub-BLMTBI118_ses-bline_run-001_T1w_template.nii.gz
outlier_sensitivity = <undefined>
scaled_intensity_outputs = <undefined>
subjects_dir = /opt/freesurfer/subjects
subsample_threshold = 200
transform_outputs = True

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/freesurfer/base.py", line 265, in run
    return super(FSCommandOpenMP, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/freesurfer/base.py", line 144, in run
    return super(FSCommand, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 758, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 695, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
mri_robust_template --satit --mov /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-BLMTBI118_ses-bline_run-001_T1w_corrected.nii.gz /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-BLMTBI118_ses-ptx_run-001_T1w_lps_corrected.nii.gz --inittp 1 --iscale --template sub-BLMTBI118_ses-bline_run-001_T1w_template.nii.gz --subsample 200 --lta /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/t1_merge/tp1.lta /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/t1_merge/tp2.lta
Standard output:
$Id: mri_robust_template.cpp,v 1.54 2016/05/05 21:17:08 mreuter Exp $

--satit: Will estimate SAT iteratively!
--mov: Using /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-BLMTBI118_ses-bline_run-001_T1w_corrected.nii.gz as movable/source volume.
--mov: Using /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-BLMTBI118_ses-ptx_run-001_T1w_lps_corrected.nii.gz as movable/source volume.
    Total: 2 input volumes
--inittp: Using TP 1 as target for initialization
--iscale: Enableing intensity scaling!
--template: Using sub-BLMTBI118_ses-bline_run-001_T1w_template.nii.gz as template output volume.
--subsample: Will subsample if size is larger than 200 on all axes!
--lta: Will output LTA transforms
Setting iscale ...
reading source '/data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-BLMTBI118_ses-bline_run-001_T1w_corrected.nii.gz'...
converting source '/data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-BLMTBI118_ses-bline_run-001_T1w_corrected.nii.gz' to bspline ...
MRItoBSpline degree 3
reading source '/data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-BLMTBI118_ses-ptx_run-001_T1w_lps_corrected.nii.gz'...
converting source '/data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-BLMTBI118_ses-ptx_run-001_T1w_lps_corrected.nii.gz' to bspline ...
MRItoBSpline degree 3

MultiRegistration::initializing Xforms (init 1 , maxres 0 , iterate 5 , epsit 0.01 ) :

[init] ========================= TP 2 to TP 1 ==============================
         Register TP 2 ( /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-BLMTBI118_ses-ptx_run-001_T1w_lps_corrected.nii.gz )
          to      TP 1 ( /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-BLMTBI118_ses-bline_run-001_T1w_corrected.nii.gz )


   - Max Resolution used: 2
     -- gpS ( 49 , 66 , 66 )
     -- gpT ( 49 , 66 , 66 )
   - running loop to estimate saturation parameter:

Input rotation's max deviation from rotation is: 2.25062e-05
  computing mean coord of TP 1 ( /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-BLMTBI118_ses-bline_run-001_T1w_corrected.nii.gz )
   mapping back to rot, err = 4.47975e-16
  computing mean coord of TP 2 ( /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso/scratch/qsiprep_wf/single_subject_BLMTBI118_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-BLMTBI118_ses-ptx_run-001_T1w_lps_corrected.nii.gz )
Standard error:
Internal Error for tp 1 -> template
 Rotation should not scale ( 1.1253e-05 )
 Debug Info:
A = [ ...
 0.9999310670458 -0.0109057024202 -0.0024357834399
 0.0108547832186  0.9997341254715 -0.0200214454704
 0.0026535009930  0.0199937553293  0.9997900854229  ]

R = [ ...
 0.9999375635465 -0.0109057732739 -0.0024357992650
 0.0108548537416  0.9997406206926 -0.0200215755487
 0.0026535182326  0.0199938852277  0.9997965810076  ]

S = [ ...
 0.9999935030937                0                0
               0  0.9999935030937 -0.0000000000000
               0 -0.0000000000000  0.9999935030937  ]

Internal Error: Rotation should not scale.

No such file or directory
Return code: 248
```

**Comment by mattcieslak** [comment]
interesting! if you don't use --longitudinal does the error go away?

**Comment by araikes** [comment]
Yes, it runs that node without issue.

**Comment by mattcieslak** [comment]
This fix is already in qsiprep, we forked fmriprep a couple years after they did that patch. If you run without --longitudinal you won't be changing the DWI workflow at all.

**Comment by araikes** [comment]
Not using `--longitudinal` appears to have work for most people. However, one person crashed when processed without the flag but processed fine with the flag:

```
Node: qsiprep_wf.single_subject_BLMTBI116_wf.dwi_preproc_ses_bline_dir_AP_run_001_wf.fmap_unwarp_report_wf.dwi_rpt
Working directory: /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso_no-long/scratch/qsiprep_wf/single_subject_BLMTBI116_wf/dwi_preproc_ses_bline_dir_AP_run_001_wf/fmap_unwarp_report_wf/dwi_rpt

Node inputs:

after = /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso_no-long/scratch/qsiprep_wf/single_subject_BLMTBI116_wf/dwi_preproc_ses_bline_dir_AP_run_001_wf/hmc_sdc_wf/b0_ref_to_lps/topup_imain_corrected_avg_unbiasedsharpened_LPS.nii.gz
before = /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso_no-long/scratch/qsiprep_wf/single_subject_BLMTBI116_wf/dwi_preproc_ses_bline_dir_AP_run_001_wf/hmc_sdc_wf/enhance_pre_sdc/topup_pre_image_unbiasedsharpened.nii.gz
compress_report = auto
out_report = report.svg
wm_seg = /data/BL2_clean/derivatives/qsiprep-0.8.0RC2/1mm-iso_no-long/scratch/qsiprep_wf/single_subject_BLMTBI116_wf/dwi_preproc_ses_bline_dir_AP_run_001_wf/fmap_unwarp_report_wf/map_seg/highres001_BrainExtractionBrain_trans_seg_trans_wm.nii.gz

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 376, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/niworkflows/interfaces/registration.py", line 312, in _post_run_hook
    return super(SimpleBeforeAfterRPT, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/mixins/reporting.py", line 47, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/niworkflows/interfaces/report_base.py", line 59, in _generate_report
    cuts = cuts_from_bbox(contour_nii, cuts=n_cuts)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/niworkflows/viz/utils.py", line 204, in cuts_from_bbox
    start_coords = B.min(0)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by araikes** [comment]
And I was wrong.. after a more complete look at the dataset, there are two individuals with the weird T1 issue if I don't deoblique first.

**Comment by araikes** [comment]
At this point, I'm deobliquing prior to QSIPrep across the board so I'm closing this. Reopen this issue if you need to @mattcieslak .
