### ISSUE TITLE
QSIprep error:  Each element of the 'bias_images_plus' trait of a ConcatRPESplitsInputSpec instance must be an existing file name

### ISSUE THREAD

**Issue by dlevitas** [PennBBL/qsiprep#116]
Hi,

I'm working with version 0.8.0RC3, running the following command:
```
unset PYTHONPATH; singularity run /N/dcwan/projects/irf/containers/qsiprep-0.8.0RC3.sif 	\
	$bids_root_dir $bids_root_dir/derivatives				 		\
	participant 													\
	--participant_label 01 											\
	--skip_bids_validation 											\
	--output-space T1w			 									\
	--combine_all_dwis 												\
	--output-resolution 1											\
	--nthreads 8											\
	--fs-license-file $FREESURFER_HOME/license.txt					\
	--stop-on-first-crash 											\
	--resource-monitor 												\
	--use-plugin $bids_root_dir/qsiprep_plugin_01.yml 			\
	-w $bids_root_dir/derivatives/qsiprep/sub-01
```

The error message I'm getting is:
```
QSIPrep failed: Each element of the 'bias_images_plus' trait of a ConcatRPESplitsInputSpec instance must be an existing file name, but a value of <undefined> <class 'traits.trait_base._Undefined'> was specified.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 566, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 589, in run
    execgraph = generate_expanded_graph(deepcopy(flatgraph))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1001, in generate_expanded_graph
    graph_in = _remove_nonjoin_identity_nodes(graph_in, keep_iterables=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 879, in _remove_nonjoin_identity_nodes
    _remove_identity_node(graph, node)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 905, in _remove_identity_node
    portinputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 983, in _propagate_internal_output
    destnode.set_input(inport, value)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 278, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 341, in validate
    value = super(MultiObject, self).validate(object, name, newvalue)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_types.py", line 2336, in validate
    return TraitListObject( self, object, name, value )
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2313, in __init__
    raise excp
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2305, in __init__
    value = [ validate( object, name, val ) for val in value ]
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2305, in <listcomp>
    value = [ validate( object, name, val ) for val in value ]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 103, in validate
    validated_value = super(File, self).validate(object, name, value)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_types.py", line 411, in validate
    self.error( object, name, value )
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: Each element of the 'bias_images_plus' trait of a ConcatRPESplitsInputSpec instance must be an existing file name, but a value of <undefined> <class 'traits.trait_base._Undefined'> was specified.
```

I believe the issue has to do with setting the ```--combine_all_dwis``` flag option, since QSIprep will run to completion if I remove it.  I'm trying to add this flag option though because I have two DWI scans collected, each with an opposing PED for SDC. 

Thanks for the help

**Comment by mattcieslak** [comment]
This should be fixed after 0.9. Please reopen if it persists
