### ISSUE TITLE
'Does not support two inline functions in series' error

### ISSUE THREAD

**Issue by robmcc10** [PennBBL/qsiprep#126]
Dear QSIprep team,

Many thanks for your work in making this available!

I have ran into a problem. I submit my job as follows:

```
singularity run --cleanenv ${HOME}/singularity_images/qsiprep-0.8.0.sif \
/home/data/qsi_test \
/home/results/dwi/qsi_test_results2 \
-w /home/results/dwi/qsi_working2/ \
participant \
--output-resolution 2 \
--recon-spec mrtrix_singleshell_ss3t \
--output-space T1w template \
--template MNI152NLin2009cAsym \
--fs-license-file ${HOME}/license.txt

```
But after passing the BIDS validation step I receive the following error:
```
### References

[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'CITATION'
QSIPrep failed: Does not support two inline functions in series ('def _get_first(lll):
    return lll[0]
'  and 'def _aslist(in_value):
    if isinstance(in_value, list):
        return in_value
    return [in_value]
'), found when connecting qsiprep_wf.single_subject_505_wf.dwi_preproc_ses_A_acq_normal_wf.b0_anat_coreg.b0_to_anat to qsiprep_wf.single_subject_505_wf.dwi_finalize_ses_A_acq_normal_wf.transform_dwis_mni.mask_merge_tfms. Please use a Function node.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 566, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 622, in run
    execgraph = generate_expanded_graph(deepcopy(flatgraph))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 975, in generate_expanded_graph
    graph_in = _remove_nonjoin_identity_nodes(graph_in, keep_iterables=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 854, in _remove_nonjoin_identity_nodes
    _remove_identity_node(graph, node)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 881, in _remove_identity_node
    _propagate_internal_output(graph, node, field, connections, portinputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 939, in _propagate_internal_output
    "node.".format(src_func, dst_func, srcnode, destnode)
ValueError: Does not support two inline functions in series ('def _get_first(lll):
    return lll[0]
'  and 'def _aslist(in_value):
    if isinstance(in_value, list):
        return in_value
    return [in_value]
'), found when connecting qsiprep_wf.single_subject_505_wf.dwi_preproc_ses_A_acq_normal_wf.b0_anat_coreg.b0_to_anat to qsiprep_wf.single_subject_505_wf.dwi_finalize_ses_A_acq_normal_wf.transform_dwis_mni.mask_merge_tfms. Please use a Function node.
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

```

When googling the only thing that seemed relevant was: [https://github.com/poldracklab/fmriprep/issues/2085](https://github.com/poldracklab/fmriprep/issues/2085)

Any advice appreciated

Thanks

Rob

**Comment by mattcieslak** [comment]
Thanks for pointing this out! I think you will be OK if you remove "template" from --output-spaces and add --force-spatial-normalization. We recommend spatially normalizing DWI outputs only after model fitting so that the registration includes useful contrast in white matter. I should remove this as an option and update the documentation to reflect this.

**Comment by robmcc10** [comment]
Thanks! That works
