### ISSUE TITLE
Plot Peaks Crashes; Does this Preclude Other Steps from Finishing?

### ISSUE THREAD

**Issue by smeisler** [PennBBL/qsiprep#195]
Hello,

I am running qsiprep (0.12.2) on single-shelled DWI data that has already been run through Freesurfer (via fmriprep). Thus, I chose the recon spec for mrtrix single-shell ss3t. I use Slurm to submit my jobs, each subject using the following code:
```
#!/bin/bash
#SBATCH -t 48:00:00                  # walltime = 2 days
#SBATCH -N 1                         #  one node
#SBATCH -n 10                         #  10 CPU (hyperthreaded) cores
#SBATCH --gres=gpu:2                 #  2 GPU
#SBATCH --constraint=high-capacity   #  high-capacity GPU

singularity run --nv --cleanenv -B /om4 -B /om /om2/user/smeisler/qsiprep_new.img     \
/om/project/PARC/BIDS/data /om/project/PARC/BIDS/derivatives/ participant --participant-label $1 \
--fs-license-file /om4/group/gablab/dti_proc/license.txt --hmc_model eddy \
 --work_dir /om/project/PARC/BIDS/derivatives/work \
--recon_spec mrtrix_singleshell_ss3t_noACT --unringing_method mrdegibbs --output_resolution 1.2
```
Where $1 is the subject label passed into the script.

QSIPrep runs fine, but QSIRecon begins to throw errors, particularly during the "plot_peaks" task which begins concurrently with tractography. Since I run these jobs in the background with sbatch, I would expect something that requires a rendered window, like plot_peaks, to fail. The last successfully outputted file appears to be the normalized FODs in the /qsirecon/$SUB/dwi folder. The error is below.

```
	 [Node] Setting-up "qsirecon_wf.sub-ABCD1727_mrtrix_singleshell_ss3t_noACT.recon_wf.ss3t_csd.plot_peaks" in "/om/project/PARC/BIDS/derivatives/work/qsirecon_wf/sub-ABCD1727_mrtrix_singleshell_ss3t_noACT/recon_wf/ss3t_csd/_dwi_file_..om..project..PARC..BIDS..derivatives..qsiprep..sub-ABCD1727..dwi..sub-ABCD1727_space-T1w_desc-preproc_dwi.nii.gz/plot_peaks".
201113-13:30:42,349 nipype.workflow INFO:
	 [Node] Running "plot_peaks" ("qsiprep.interfaces.reports.ReconPeaksReport")
201113-13:31:48,948 nipype.workflow INFO:
	 b''
201113-13:31:48,948 nipype.workflow INFO:
	 b''
ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 291
vtkXOpenGLRenderWindow (0x55b472eeae80): Could not find a decent config


ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 291
vtkXOpenGLRenderWindow (0x55b472eeae80): Could not find a decent config


ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 291
vtkXOpenGLRenderWindow (0x55b472eeae80): Could not find a decent config


ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 606
vtkXOpenGLRenderWindow (0x55b472eeae80): Cannot create GLX context.  Aborting.

Fatal Python error: Aborted

Current thread 0x00002b334da455c0 (most recent call first):
  File "/usr/local/miniconda/lib/python3.7/site-packages/fury/window.py", line 827 in record
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/niworkflows/viz/utils.py", line 847 in plot_peak_slice
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/niworkflows/viz/utils.py", line 867 in peak_slice_series
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/reports.py", line 745 in _run_interface
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419 in run
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741 in _run_command
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635 in _run_interface
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516 in run
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67 in run_node
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 232 in _process_worker
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99 in run
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297 in _bootstrap
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/spawn.py", line 118 in _main
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/forkserver.py", line 297 in _serve_one
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/forkserver.py", line 261 in main
  File "<string>", line 1 in <module>
exception calling callback for <Future at 0x2ba18e21d9b0 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
exception calling callback for <Future at 0x2ba18e21d710 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
However, the slurm jobs have not cancelled yet. My question is **does a failure in plot_peaks preclude the rest of the code from finishing?** If so, should I be submitting jobs in another way that would allow for window rendering? I plan on waiting to see what happens regardless, but knowing the nature of tractography, I could be waiting for quite a bit.

Thanks,
Steven

**Comment by mattcieslak** [comment]
Hi Steven,
Thanks for reporting this. I've seen this sometimes on machines with older hardware. As long as you don't have `--stop-on-first-crash` enabled the rest of the workflow will run and you will have usable outputs. The reports just won't have the peaks plotted. Are you able to start an xvfb on the compute host?

**Comment by smeisler** [comment]
Thanks for the quick response! I do not have that argument enabled, so looks like I'm in the clear. I see that Xvfb is installed on the server, although I haven't used it yet or know the syntax. Would a fix be as easy as prepending `xvfb-run [OPTIONS]` to the singularity call? If it's more complicated than that, don't worry about typing it all out; I can just ask our server admin for guidance.

**Comment by droediger** [comment]
I ran into this same error today and it does seem to cause everything to grind to a seemingly indefinite halt (the container hasn't gone above 7% CPU usage for 6 hours and no new processes have started).

**Comment by smeisler** [comment]
I looked into the `/work/qsirecon_wf/......./recon_wf/track_ifod2/..../tractography/` folder and saw that the `tracked.tck` has been stuck at a small file size (~70 MB) for a while, so I think my jobs have stalled too unfortunately, although the Slurm batches are still technically active.

**Comment by mattcieslak** [comment]
Could you try using just a single CPU, adding an extra day to the run time and making sure you have a ton of memory available? I wonder if the tractography is having trouble allocating memory for all those cpus.

**Comment by smeisler** [comment]
Sure! I'll try 32 gb and report back.

**Comment by smeisler** [comment]
Tractography seems to have stalled again. tracked.tck maxes out around 1.3 KB.

**Comment by mattcieslak** [comment]
did you specify on the command line `--nthreads 1`?

**Comment by smeisler** [comment]
No, will specify that now, and try increasing the memory to 50gb

**Comment by smeisler** [comment]
So far it appears to be working (~2 GB for the .tck file and growing)!

**Comment by mattcieslak** [comment]
excellent! you could probably speed it up by setting --nthreads to something < 8 and requesting 8 or more cpus from slurm. I think qsiprep may have been detecting all the cpus available on the compute host and trying to parallelize over all of them.

**Comment by droediger** [comment]
I'm still struggling with this. Setting nthreads to 1 doesn't appear to help.

I get the same plot_peaks error as smeisler, but in my case the tractography doesn't appear to launch at all after the error (tckgen isn't running, no .tck file is created anywhere in the wf). 

Some other differences between my case and smeisler: I'm running mrtrix_multishell_msmt rather than the ss3t workflow. Also, I'm running the Singularity container (0.12.2) interactively over an NX session rather than as a SLURM job.

**Comment by mattcieslak** [comment]
@droediger do you have the `--stop-on-first-crash` option enabled?

**Comment by droediger** [comment]
@mattcieslak Nope. However, I moved things over to a high memory SLURM partition and it's running fine now 👍
