### ISSUE TITLE
Traits Error on Basic Command Line

### ISSUE THREAD

**Issue by ShreyasFadnavis** [PennBBL/qsiprep#196]
I tried running the following command:
`qsiprep data-dir derivative-dir participant -w data-dir --dwi-denoise-window 5 --output-resolution 1.2 `

For which I got the following error log:

```
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
bids-validator does not appear to be installed
201117-14:26:03,739 nipype.workflow INFO:
	 Running with omp_nthreads=8, nthreads=16
201117-14:26:03,740 nipype.workflow IMPORTANT:
	 
    Running qsiprep version 0.12.2:
      * BIDS dataset path: /blah.
      * Participant list: ['001', '002'].
      * Run identifier: 20201117-142603_fcc5c71e-85d3-4ee9-8a75-9c180d7425c2.
    
Process Process-2:
Traceback (most recent call last):
  File "/data1/miniconda3/envs/mlenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data1/miniconda3/envs/mlenv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/shreyas/.local/lib/python3.7/site-packages/qsiprep/cli/run.py", line 927, in build_qsiprep_workflow
    force_syn=opts.force_syn
  File "/home/shreyas/.local/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 269, in init_qsiprep_wf
    force_syn=force_syn)
  File "/home/shreyas/.local/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 560, in init_single_subject_wf
    num_t1w=len(subject_data['t1w']))
  File "/home/shreyas/.local/lib/python3.7/site-packages/qsiprep/workflows/anatomical.py", line 294, in init_anat_preproc_wf
    omp_nthreads=omp_nthreads)
  File "/home/shreyas/.local/lib/python3.7/site-packages/qsiprep/workflows/anatomical.py", line 753, in init_skullstrip_ants_wf
    rigid_acpc_align.inputs.fixed_image = acpc_template
  File "/home/shreyas/.local/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 426, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/home/shreyas/.local/lib/python3.7/site-packages/traits/trait_types.py", line 2473, in validate
    return TraitListObject(self, object, name, value)
  File "/home/shreyas/.local/lib/python3.7/site-packages/traits/trait_list_object.py", line 582, in __init__
    notifiers=[self.notifier],
  File "/home/shreyas/.local/lib/python3.7/site-packages/traits/trait_list_object.py", line 210, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/home/shreyas/.local/lib/python3.7/site-packages/traits/trait_list_object.py", line 210, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/home/shreyas/.local/lib/python3.7/site-packages/traits/trait_list_object.py", line 862, in _item_validator
    return trait_validator(object, self.name, value)
  File "/home/shreyas/.local/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/home/shreyas/.local/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/home/shreyas/.local/lib/python3.7/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'fixed_image' trait of a RegistrationInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/shreyas/.local/lib/python3.7/site-packages/qsiprep/data/mni_1mm_t1w_lps_brain.nii.gz' <class 'str'> was specified.
```

Any suggestions on what I am doing wrong?

**Comment by ShreyasFadnavis** [comment]
Okay: Seems like the `mni_1mm_t1w_lps_brain.nii.gz` template is missing 👍  Still reporting this, just in case...
