### ISSUE TITLE
ImportError: cannot import name 'NUMPY_MMAP' from 'nipype.utils'

### ISSUE THREAD

**Issue by LTomova** [PennBBL/qsiprep#201]
Hello, 

I'm trying to run qsiprep version 0.11.0 via singularity on a HPC. Processing of the anatomical data works fine but it crashes when processing the DWI data running
qsiprep_wf.single_subject_pilot01_wf.dwi_preproc_acq_DTI2_wf.hmc_sdc_wf.sdc_wf.phdiff_wf.demean

Here is the full error message:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)
  File "<string>", line 8, in demean_image
ImportError: cannot import name 'NUMPY_MMAP' from 'nipype.utils' (/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/__init__.py)

Can someone help me with this? 

Thank you!
Livia

**Comment by mattcieslak** [comment]
Hi! Could you please try upgrading the singularity image? This was a bug in 0.11 (#172) that we fixed. Our current release is 0.12.2

**Comment by IRuotsa** [comment]
Hi, I did not see this information in the "what's new" -site (https://qsiprep.readthedocs.io/en/latest/changes.html). Could it be possible to update the latest version there? It would be helpful especially when installing using singularity, because the specific version should be specified, and not sure where to find the details concerning the latest version. Thanks!

**Comment by LTomova** [comment]
Thank you @mattcieslak, I updated the singularity image and now everything works! I agree with @IRuotsa that it would be very helpful to have more details on the latest version in the documentations - I thought 0.11.0 was the latest version and therefore used it.

Thank you!

Livia
