### ISSUE TITLE
DSI raw_gqi Assertion Error len(results) !=1 

### ISSUE THREAD

**Issue by bwinsto2** [PennBBL/qsiprep#204]
Hi--running qsiprep 0.12.2 singularity image on raw HCP data BIDSified using hcp2bids. I've printed below my singularity command, the error, and the directory structure for a subject. Would love any help with this issue! Thanks.

```
singularity run --cleanenv --nv -B /data/hpc900:/data/hpc900 qsiprep-0.12.2.sif /data/hpc900/test-data-bids /data/hpc900/bwinston/qsiprep/output participant \ 
--work_dir /data/hpc900/bwinston/qsiprep/work_dir \
--fs-license-file /data/hpc900/bwinston/license.txt \
--output-resolution 1.25 --output-space T1w --distortion-group-merge average \
--participant-label 128026 --combine-all-dwis --hmc-model eddy --stop-on-first-crash \
--eddy-config /data/hpc900/bwinston/cuda_eddy_params.json 
```
Error (note: i shortened some of the filepaths):
  ```
201215-16:18:51,587 nipype.workflow INFO:
	 [Node] Running "raw_gqi" ("qsiprep.interfaces.dsi_studio.DSIStudioGQIReconstruction"), a CommandLine Interface with command:
dsi_studio --action=rec --method=4 --check_btable=0 --source=/bwinston/qsiprep/work_dir/qsiprep_wf/single_subject_128026_wf/dwi_pr
eproc_wf/pre_hmc_wf/dwi_qc_wf/raw_gqi/sub-128026_acq-dir95rl_dwi_merged_merged.src.gz --threads=1 --num_fiber=3 --record_odf=1 --param0=1.2500 --thread_count=
1
201215-16:18:59,798 nipype.workflow INFO:
	 [Node] Running "raw_src_qc" ("qsiprep.interfaces.dsi_studio.DSIStudioSrcQC")
current dir /bwinston/qsiprep/work_dir/qsiprep_wf/single_subject_128026_wf/dwi_preproc_wf/pre_hmc_wf/dwi_qc_wf/raw_gqi
input src /bwinston/qsiprep/work_dir/qsiprep_wf/single_subject_128026_wf/dwi_preproc_wf/pre_hmc_wf/dwi_qc_wf/raw_gqi/sub-128026_ac
q-dir95rl_dwi_merged_merged.src.gz
split src name sub-128026_acq-dir95rl_dwi_merged_merged.src.gz
search target /bwinston/qsiprep/work_dir/qsiprep_wf/single_subject_128026_wf/dwi_preproc_wf/pre_hmc_wf/dwi_qc_wf/raw_gqi/sub-12802
6_acq-dir95rl_dwi_merged_merged.src.gz*gqi*.fib.gz
201215-16:19:19,424 nipype.workflow WARNING:
	 Storing result file without outputs
201215-16:19:19,443 nipype.workflow WARNING:
	 [Node] Error on "qsiprep_wf.single_subject_128026_wf.dwi_preproc_wf.pre_hmc_wf.dwi_qc_wf.raw_gqi" (/bwinston/qsiprep/work
_dir/qsiprep_wf/single_subject_128026_wf/dwi_preproc_wf/pre_hmc_wf/dwi_qc_wf/raw_gqi)
201215-16:19:21,241 nipype.workflow ERROR:
	 Node raw_gqi failed to run on host compute-117.cm.cluster.
201215-16:19:21,245 nipype.workflow ERROR:
	 Saving crash info to /bwinston/qsiprep/output/qsiprep/sub-128026/log/20201215-151323_ef470356-486d-4ed9-9f0a-4da425e46d64
/crash-20201215-161921-bwinston-raw_gqi-1bb695cb-2b28-48d4-b244-8f4a0ceb3bdf.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 421, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 498, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/dsi_studio.py", line 261, in _list_outputs
    assert len(results) == 1
AssertionError

201215-16:19:27,664 nipype.interface INFO:
	 b'DSI Studio Oct 26 2020, Fang-Cheng Yeh\nsource=/bwinston/qsiprep/work_dir/qsiprep_wf/single_subject_128026_wf/dwi_prepr
oc_wf/pre_hmc_wf/dwi_qc_wf/raw_src_qc/src_qc\naction=qc\nquality control checking src files in /bwinston/qsiprep/work_dir/qsiprep_
wf/single_subject_128026_wf/dwi_preproc_wf/pre_hmc_wf/dwi_qc_wf/raw_src_qc/src_qc\na total of 1 SRC file(s) were found.\nchecking /bwinston/qsiprep/work_dir/qsiprep_wf/single_subject_128026_wf/dwi_preproc_wf/pre_hmc_wf/dwi_qc_wf/raw_src_qc/src_qc/sub-128026_acq-dir95rl_dwi_merged_merged.
src.gz\nResource temporarily unavailable\n'
201215-16:19:28,466 nipype.workflow INFO:
	 [Node] Finished "qsiprep_wf.single_subject_128026_wf.dwi_preproc_wf.pre_hmc_wf.dwi_qc_wf.raw_src_qc".
[jhpce01 /users/bwinston]$ 

```
Here's from the crash log:
```
Node inputs:

args = <undefined>
check_btable = 0
decomp_fraction = <undefined>
decomp_m_value = <undefined>
decomposition = <undefined>
deconv_regularization = <undefined>
deconvolution = <undefined>
environ = {}
grad_dev = <undefined>
input_src_file = <undefined>
mask = <undefined>
nthreads = 1
num_fibers = 3
odf_order = 8
output_odf = True
ratio_of_mean_diffusion_distance = 1.25
thread_count = 1

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 421, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 498, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/dsi_studio.py", line 261, in _list_outputs
    assert len(results) == 1
AssertionError
```
I'm not sure what could be wrong in my singularity command, so I'm assuming it's something with my BIDS data. The only potential issue I see with this dataset is the filenames of the dwi files--they are e.g. `acq-dir95lr` rather than `acq-95_dir-lr`. I don't think this should make any difference, though, b/c the filenames are just for reference, and all the relevant PE directions are in the json files. `acq-dir95lr` `acq-dir96lr` and `acq-dir97lr` all have the same PE direction, but it seems like that should be fine since you did something similar in #129 and I'm using `--distortion-group-average`

Here is the directory structure for a subject's folder:

```
/test-data-bids
├── dataset_description.json
├── sub-128026
│   ├── anat
│   │   ├── sub-128026_run-01_T1w.nii.gz
│   │   └── sub-128026_run-01_T2w.nii.gz
│   ├── dwi
│   │   ├── sub-128026_acq-dir95lr_dwi.bval
│   │   ├── sub-128026_acq-dir95lr_dwi.bvec
│   │   ├── sub-128026_acq-dir95lr_dwi.json
│   │   ├── sub-128026_acq-dir95lr_dwi.nii.gz
│   │   ├── sub-128026_acq-dir95lr_sbref.json
│   │   ├── sub-128026_acq-dir95lr_sbref.nii.gz
│   │   ├── sub-128026_acq-dir95rl_dwi.bval
│   │   ├── sub-128026_acq-dir95rl_dwi.bvec
│   │   ├── sub-128026_acq-dir95rl_dwi.json
│   │   ├── sub-128026_acq-dir95rl_dwi.nii.gz
│   │   ├── sub-128026_acq-dir95rl_sbref.json
│   │   ├── sub-128026_acq-dir95rl_sbref.nii.gz
│   │   ├── sub-128026_acq-dir96lr_dwi.bval
│   │   ├── sub-128026_acq-dir96lr_dwi.bvec
│   │   ├── sub-128026_acq-dir96lr_dwi.json
│   │   ├── sub-128026_acq-dir96lr_dwi.nii.gz
│   │   ├── sub-128026_acq-dir96lr_sbref.json
│   │   ├── sub-128026_acq-dir96lr_sbref.nii.gz
│   │   ├── sub-128026_acq-dir96rl_dwi.bval
│   │   ├── sub-128026_acq-dir96rl_dwi.bvec
│   │   ├── sub-128026_acq-dir96rl_dwi.json
│   │   ├── sub-128026_acq-dir96rl_dwi.nii.gz
│   │   ├── sub-128026_acq-dir96rl_sbref.json
│   │   ├── sub-128026_acq-dir96rl_sbref.nii.gz
│   │   ├── sub-128026_acq-dir97lr_dwi.bval
│   │   ├── sub-128026_acq-dir97lr_dwi.bvec
│   │   ├── sub-128026_acq-dir97lr_dwi.json
│   │   ├── sub-128026_acq-dir97lr_dwi.nii.gz
│   │   ├── sub-128026_acq-dir97lr_sbref.json
│   │   ├── sub-128026_acq-dir97lr_sbref.nii.gz
│   │   ├── sub-128026_acq-dir97rl_dwi.bval
│   │   ├── sub-128026_acq-dir97rl_dwi.bvec
│   │   ├── sub-128026_acq-dir97rl_dwi.json
│   │   ├── sub-128026_acq-dir97rl_dwi.nii.gz
│   │   ├── sub-128026_acq-dir97rl_sbref.json
│   │   └── sub-128026_acq-dir97rl_sbref.nii.gz
│   ├── fmap
│   │   ├── sub-128026_dir-10_epi.json
│   │   ├── sub-128026_dir-10_epi.nii.gz
│   │   ├── sub-128026_dir-11_epi.json
│   │   ├── sub-128026_dir-11_epi.nii.gz
│   │   ├── sub-128026_dir-12_epi.json
│   │   ├── sub-128026_dir-12_epi.nii.gz
│   │   ├── sub-128026_dir-13_epi.json
│   │   ├── sub-128026_dir-13_epi.nii.gz
│   │   ├── sub-128026_dir-14_epi.json
│   │   ├── sub-128026_dir-14_epi.nii.gz
│   │   ├── sub-128026_dir-15_epi.json
│   │   ├── sub-128026_dir-15_epi.nii.gz
│   │   ├── sub-128026_dir-16_epi.json
│   │   ├── sub-128026_dir-16_epi.nii.gz
│   │   ├── sub-128026_dir-17_epi.json
│   │   ├── sub-128026_dir-17_epi.nii.gz
│   │   ├── sub-128026_dir-18_epi.json
│   │   ├── sub-128026_dir-18_epi.nii.gz
│   │   ├── sub-128026_dir-19_epi.json
│   │   ├── sub-128026_dir-19_epi.nii.gz
│   │   ├── sub-128026_dir-1_epi.json
│   │   ├── sub-128026_dir-1_epi.nii.gz
│   │   ├── sub-128026_dir-20_epi.json
│   │   ├── sub-128026_dir-20_epi.nii.gz
│   │   ├── sub-128026_dir-21_epi.json
│   │   ├── sub-128026_dir-21_epi.nii.gz
│   │   ├── sub-128026_dir-22_epi.json
│   │   ├── sub-128026_dir-22_epi.nii.gz
│   │   ├── sub-128026_dir-23_epi.json
│   │   ├── sub-128026_dir-23_epi.nii.gz
│   │   ├── sub-128026_dir-24_epi.json
│   │   ├── sub-128026_dir-24_epi.nii.gz
│   │   ├── sub-128026_dir-25_epi.json
│   │   ├── sub-128026_dir-25_epi.nii.gz
│   │   ├── sub-128026_dir-26_epi.json
│   │   ├── sub-128026_dir-26_epi.nii.gz
│   │   ├── sub-128026_dir-27_epi.json
│   │   ├── sub-128026_dir-27_epi.nii.gz
│   │   ├── sub-128026_dir-28_epi.json
│   │   ├── sub-128026_dir-28_epi.nii.gz
│   │   ├── sub-128026_dir-29_epi.json
│   │   ├── sub-128026_dir-29_epi.nii.gz
│   │   ├── sub-128026_dir-2_epi.json
│   │   ├── sub-128026_dir-2_epi.nii.gz
│   │   ├── sub-128026_dir-30_epi.json
│   │   ├── sub-128026_dir-30_epi.nii.gz
│   │   ├── sub-128026_dir-31_epi.json
│   │   ├── sub-128026_dir-31_epi.nii.gz
│   │   ├── sub-128026_dir-32_epi.json
│   │   ├── sub-128026_dir-32_epi.nii.gz
│   │   ├── sub-128026_dir-33_epi.json
│   │   ├── sub-128026_dir-33_epi.nii.gz
│   │   ├── sub-128026_dir-34_epi.json
│   │   ├── sub-128026_dir-34_epi.nii.gz
│   │   ├── sub-128026_dir-35_epi.json
│   │   ├── sub-128026_dir-35_epi.nii.gz
│   │   ├── sub-128026_dir-36_epi.json
│   │   ├── sub-128026_dir-36_epi.nii.gz
│   │   ├── sub-128026_dir-3_epi.json
│   │   ├── sub-128026_dir-3_epi.nii.gz
│   │   ├── sub-128026_dir-4_epi.json
│   │   ├── sub-128026_dir-4_epi.nii.gz
│   │   ├── sub-128026_dir-5_epi.json
│   │   ├── sub-128026_dir-5_epi.nii.gz
│   │   ├── sub-128026_dir-6_epi.json
│   │   ├── sub-128026_dir-6_epi.nii.gz
│   │   ├── sub-128026_dir-7_epi.json
│   │   ├── sub-128026_dir-7_epi.nii.gz
│   │   ├── sub-128026_dir-8_epi.json
│   │   ├── sub-128026_dir-8_epi.nii.gz
│   │   ├── sub-128026_dir-9_epi.json
│   │   ├── sub-128026_dir-9_epi.nii.gz
│   │   ├── sub-128026_run-01_magnitude.nii.gz
│   │   ├── sub-128026_run-01_phasediff.json
│   │   ├── sub-128026_run-01_phasediff.nii.gz
│   │   ├── sub-128026_run-02_magnitude.nii.gz
│   │   ├── sub-128026_run-02_phasediff.json
│   │   └── sub-128026_run-02_phasediff.nii.gz
│   └── func
│       ├── sub-128026_task-EMOTION_acq-LR_bold.nii.gz
│       ├── sub-128026_task-EMOTION_acq-LR_sbref.nii.gz
│       ├── sub-128026_task-EMOTION_acq-RL_bold.nii.gz
│       ├── sub-128026_task-EMOTION_acq-RL_sbref.nii.gz
│       ├── sub-128026_task-GAMBLING_acq-LR_bold.nii.gz
│       ├── sub-128026_task-GAMBLING_acq-LR_sbref.nii.gz
│       ├── sub-128026_task-GAMBLING_acq-RL_bold.nii.gz
│       ├── sub-128026_task-GAMBLING_acq-RL_sbref.nii.gz
│       ├── sub-128026_task-LANGUAGE_acq-LR_bold.nii.gz
│       ├── sub-128026_task-LANGUAGE_acq-LR_sbref.nii.gz
│       ├── sub-128026_task-LANGUAGE_acq-RL_bold.nii.gz
│       ├── sub-128026_task-LANGUAGE_acq-RL_sbref.nii.gz
│       ├── sub-128026_task-MOTOR_acq-LR_bold.nii.gz
│       ├── sub-128026_task-MOTOR_acq-LR_sbref.nii.gz
│       ├── sub-128026_task-MOTOR_acq-RL_bold.nii.gz
│       ├── sub-128026_task-MOTOR_acq-RL_sbref.nii.gz
│       ├── sub-128026_task-RELATIONAL_acq-LR_bold.nii.gz
│       ├── sub-128026_task-RELATIONAL_acq-LR_sbref.nii.gz
│       ├── sub-128026_task-RELATIONAL_acq-RL_bold.nii.gz
│       ├── sub-128026_task-RELATIONAL_acq-RL_sbref.nii.gz
│       ├── sub-128026_task-REST_run-01_sbref.nii.gz
│       ├── sub-128026_task-REST_run-02_sbref.nii.gz
│       ├── sub-128026_task-SOCIAL_acq-LR_bold.nii.gz
│       ├── sub-128026_task-SOCIAL_acq-LR_sbref.nii.gz
│       ├── sub-128026_task-SOCIAL_acq-RL_bold.nii.gz
│       ├── sub-128026_task-SOCIAL_acq-RL_sbref.nii.gz
│       ├── sub-128026_task-WM_acq-LR_bold.nii.gz
│       ├── sub-128026_task-WM_acq-LR_sbref.nii.gz
│       ├── sub-128026_task-WM_acq-RL_bold.nii.gz
│       └── sub-128026_task-WM_acq-RL_sbref.nii.gz
├── task-EMOTION_acq-LR_bold.json
├── task-EMOTION_acq-LR_sbref.json
├── task-EMOTION_acq-RL_bold.json
├── task-EMOTION_acq-RL_sbref.json
├── task-GAMBLING_acq-LR_bold.json
├── task-GAMBLING_acq-LR_sbref.json
├── task-GAMBLING_acq-RL_bold.json
├── task-GAMBLING_acq-RL_sbref.json
├── task-LANGUAGE_acq-LR_bold.json
├── task-LANGUAGE_acq-LR_sbref.json
├── task-LANGUAGE_acq-RL_bold.json
├── task-LANGUAGE_acq-RL_sbref.json
├── task-MOTOR_acq-LR_bold.json
├── task-MOTOR_acq-LR_sbref.json
├── task-MOTOR_acq-RL_bold.json
├── task-MOTOR_acq-RL_sbref.json
├── task-RELATIONAL_acq-LR_bold.json
├── task-RELATIONAL_acq-LR_sbref.json
├── task-RELATIONAL_acq-RL_bold.json
├── task-RELATIONAL_acq-RL_sbref.json
├── task-REST_acq-LR_bold.json
├── task-REST_acq-LR_sbref.json
├── task-REST_acq-RL_bold.json
├── task-REST_acq-RL_sbref.json
├── task-SOCIAL_acq-LR_bold.json
├── task-SOCIAL_acq-LR_sbref.json
├── task-SOCIAL_acq-RL_bold.json
├── task-SOCIAL_acq-RL_sbref.json
├── task-WM_acq-LR_bold.json
├── task-WM_acq-LR_sbref.json
├── task-WM_acq-RL_bold.json
└── task-WM_acq-RL_sbref.json

5 directories, 179 files
```
 Any ideas? Thanks!!

**Comment by mattcieslak** [comment]
How stable is the filesystem you're running this on? I haven't seen this error before:

```
\nchecking /bwinston/qsiprep/work_dir/qsiprep_wf/single_subject_128026_wf/dwi_preproc_wf/pre_hmc_wf/dwi_qc_wf/raw_src_qc/src_qc/sub-128026_acq-dir95rl_dwi_merged_merged.
src.gz\nResource temporarily unavailable\n'
```

The `Resource temporarily unavailable` message makes it sound like either you're on a NFS mount that went down, or maybe too many processes are being launched simultaneously. Can you try with `--nthreads` set to something less than the number of CPUs on your compute host?

**Comment by bwinsto2** [comment]
Indeed--this was an issue with the GPU, not qsiprep. Thank you.
