### ISSUE TITLE
Codec Issue?

### ISSUE THREAD

**Issue by smeisler** [PennBBL/qsiprep#210]
Hi QSIPrep Team,

I am getting the following error when running QSIPrep 0.12.2 via Singularity (Linux HPC):
```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 760, in build_qsiprep_workflow
    layout = BIDSLayout(str(bids_dir), validate=False)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 252, in __init__
    indexer.index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 214, in index_metadata
    payload = json.load(handle)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/miniconda/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```

This the command I am using, and it has worked on other datasets:

`singularity run -B ${scratch}:/workdir -B ${bids_dir}:/mnt:ro -B ${output_dir}:/output -B license.txt:/license.txt $IMG --participant_label ${subject:4} --template MNI152NLin2009cAsym --mem-mb 20000 -w /workdir --fs-license-file /license.txt --unringing_method mrdegibbs --output_resolution 1.2 --hmc_model eddy --skip-bids-validation /mnt /output participant`, where $scratch, $bids_dir, $output_dir, $subject, and $IMG are defined in the SLURM group batch submission code.

The primary thing that sets this dataset apart, to my knowledge, is it has reverse phase encoded b0 images. Here is the directory structure

```
- sub-XXX
- - anat
- - - sub-XXX_run-1_T1w.json
- - - sub-XXX_run-1_T1w.nii.gz
- - dwi
- - - sub-XXX_run-1_dwi.json
- - - sub-XXX_run-1_dwi.nii.gz
- - - sub-XXX_run-1_dwi.bval
- - - sub-XXX_run-1_dwi.bvec
- - - sub-XXX_acq-topup_run-1_dwi.nii.gz
- - - sub-XXX_acq-topup_run-1_dwi.json
- - fmap
- - - sub-XXX_run-1_phasediff.json
- - - sub-XXX_run-1_phasediff.nii.gz
- - func
- - - ........
- - sub-XXX_scans.tsv
```

Is the naming convention wrong for the files to be used for topup, or do you think there might be another issue?

Thanks,
Steven

**Comment by mattcieslak** [comment]
Hi Steven, This error comes up when there is a nifti file that has accidentally been named .json. Could you check that the bids validator says this dataset is ok?

**Comment by smeisler** [comment]
Hi Matt,

I'm getting a litany of errors, but none that indicate where this file extension confusion may be.  I'll investigate this further.
```
	[31m1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)[39m
		./audio_recordings/Aligned SWE/Final Word.docx
			Evidence: Final Word.docx
		./audio_recordings/Aligned SWE/LEAP_002_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
			Evidence: LEAP_002_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
		./audio_recordings/Aligned SWE/LEAP_004_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
			Evidence: LEAP_004_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
		./audio_recordings/Aligned SWE/LEAP_005_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
			Evidence: LEAP_005_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
		./audio_recordings/Aligned SWE/LEAP_007_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
			Evidence: LEAP_007_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
		./audio_recordings/Aligned SWE/LEAP_010_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
			Evidence: LEAP_010_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
		./audio_recordings/Aligned SWE/LEAP_012_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
			Evidence: LEAP_012_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
		./audio_recordings/Aligned SWE/LEAP_015_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
			Evidence: LEAP_015_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
		./audio_recordings/Aligned SWE/LEAP_017_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
			Evidence: LEAP_017_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
		./audio_recordings/Aligned SWE/LEAP_050_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
			Evidence: LEAP_050_TEMPLATE_TOWRE_SWE_LEXI.TextGrid
		[31m... and 118 more files having this issue (Use --verbose to see them all).[39m

[36m	Please visit https://neurostars.org/search?q=NOT_INCLUDED for existing conversations about this issue.[39m

	[31m2: [ERR] DWI scans should have a corresponding .bvec file. (code: 32 - DWI_MISSING_BVEC)[39m
		./sub-leap075/dwi/sub-leap075_acq-topup_run-1_dwi.nii.gz

[36m	Please visit https://neurostars.org/search?q=DWI_MISSING_BVEC for existing conversations about this issue.[39m

	[31m3: [ERR] DWI scans should have a corresponding .bval file. (code: 33 - DWI_MISSING_BVAL)[39m
		./sub-leap075/dwi/sub-leap075_acq-topup_run-1_dwi.nii.gz

[36m	Please visit https://neurostars.org/search?q=DWI_MISSING_BVAL for existing conversations about this issue.[39m

	[31m4: [ERR] The value of (EchoTime2 - EchoTime1) should be within the range of 0.0001 - 0.01. (code: 83 - ECHOTIME1_2_DIFFERENCE_UNREASONABLE)[39m
		./sub-leap075/fmap/sub-leap075_run-1_phasediff.nii.gz

[36m	Please visit https://neurostars.org/search?q=ECHOTIME1_2_DIFFERENCE_UNREASONABLE for existing conversations about this issue.[39m


        [34m[4mSummary:[24m[39m                   [34m[4mAvailable Tasks:[24m[39m                           [34m[4mAvailable Modalities:[24m[39m 
        3004 Files, 90.92GB        face                                       T1w                   
        73 - Subjects              obj                                        dwi                   
        1 - Session                rest                                       bold                  
                                   speech                                     events                
                                   text                                       fieldmap              
                                   backspeech                                                       
                                   TODO: full task name for face                                    
                                   TODO: full task name for obj                                     
                                   TODO: full task name for speech                                  
                                   TODO: full task name for rest                                    
                                   TODO: full task name for text                                    
                                   TODO: full task name for backspeech                              


[36m	If you have any questions, please post on https://neurostars.org/tags/bids.[39m

Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 760, in build_qsiprep_workflow
    layout = BIDSLayout(str(bids_dir), validate=False)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 252, in __init__
    indexer.index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 214, in index_metadata
    payload = json.load(handle)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/miniconda/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```

**Comment by smeisler** [comment]
I created a new bids directory without the stimuli files (the "audio_recordings" folder in the error above), and now it appears to be running.
