### ISSUE TITLE
error due to pe_direction not being detected

### ISSUE THREAD

**Issue by jeffrey-phillips** [PennBBL/qsiprep#227]
Hi folks,

I have run qsiprep through the Flywheel gear qsiprep-fw v0.3.18_0.10.0, and my jobs are failing with a TraitError related to the pe_direction variable (please see below). The input DTI data has PhaseEncodingAxis set to "j", according to the Flywheel GUI. I am unsure if the error reflects a qsiprep code issue or a problem with the DTI metadata, but your feedback would be appreciated. I am happy to supply more info as helpful.

Thanks,

Jeff

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 884, in build_qsiprep_workflow
    force_syn=opts.force_syn
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 261, in init_qsiprep_wf
    force_syn=force_syn)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 692, in init_single_subject_wf
    source_file=source_file
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/dwi/base.py", line 431, in init_dwi_preproc_wf
    output_spaces=output_spaces),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 611, in __init__
    from_file=from_file, resource_monitor=resource_monitor, **inputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 183, in __init__
    self.inputs = self.input_spec(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/specs.py", line 66, in __init__
    super(BaseTraitedSpec, self).__init__(**kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'pe_direction' trait of a DiffusionSummaryInputSpec instance must be None or 'i' or 'i-' or 'j' or 'j-', but a value of '' <class 'str'> was specified.

**Comment by mattcieslak** [comment]
Unfortunately the PhaseEncodingDirection field is necessary to determine what the distortions are. If you're not using fieldmaps you can put any of the allowed values in there. If you are using fieldmaps, you'll need to figure out which (the fieldmap or the dwi) has a positive or negative blip and fill out the field either manually or through the flywheel sdk.

**Comment by jeffrey-phillips** [comment]
Hi Matt,

Thanks for responding. I was looking for a way to specify pe_direction but
saw that it was not a config option. Should it be specified as a field in
the recon_spec file? And is there a good place to look for example
recon_specs?

Jeff

**Comment by mattcieslak** [comment]
The PhaseEncodingDirection is specified in the metadata of the DWI files. Since you're on Flywheel you can edit this info on the scan's container through the SDK or website

**Comment by jeffrey-phillips** [comment]
Thanks, Matt, I'll do that. These are Philips DTI data, and apparently it's
a known problem that Philips does not record the polarity of the phase
encoding:

https://github.com/rordenlab/dcm2niix/issues/279

Jeff
