### ISSUE TITLE
Reconstruction - mrconvert: [ERROR] error writing back contents of file

### ISSUE THREAD

**Issue by IRuotsa** [PennBBL/qsiprep#228]
Hi again!
I'm running the reconstruction pipeline for qsiprep preprocessed files and run into an error when using mrconvert. Everything seems to run ok for a quite a while, but fails to finish. I've been trying to figure this out, but don't know what's wrong here. Do you have any suggestions? 

Reconstruction command:
`singularity run --cleanenv /usr/local/qsiprep/qsiprep-0.13.0RC1.sif /nashome3/aaa/Desktop/bids /nashome3/aaa/Desktop/bids/derivatives/qsiprep_recon participant --participant-label “list of labels” --recon-only --recon_input /nashome3/aaa/Desktop/bids/derivatives/qsiprep --recon_spec mrtrix_singleshell_ss3t --fs-license-file /nashome3/aaa/Desktop/bids/sourcedata/license.txt`

Error log:
```
Node: qsirecon_wf.sub-005_mrtrix_singleshell_ss3t.recon_wf.ss3t_csd.create_mif
Working directory: /nashome3/aaa/Desktop/work/qsirecon_wf/sub-005_mrtrix_singleshell_ss3t/recon_wf/ss3t_csd/_dwi_file_..nashome3..aaa..Desktop..bids..derivatives..qsiprep..sub-005..dwi..sub-005_space-T1w_desc-preproc_dwi.nii.gz/create_mif

Node inputs:
b_file = /nashome3/aaa/Desktop/bids/derivatives/qsiprep/sub-005/dwi/sub-005_space-T1w_desc-preproc_dwi.b
bval_file = /nashome3/aaa/Desktop/bids/derivatives/qsiprep/sub-005/dwi/sub-005_space-T1w_desc-preproc_dwi.bval
bvec_file = /nashome3/aaa/Desktop/bids/derivatives/qsiprep/sub-005/dwi/sub-005_space-T1w_desc-preproc_dwi.bvec
dwi_file = /nashome3/aaa/Desktop/bids/derivatives/qsiprep/sub-005/dwi/sub-005_space-T1w_desc-preproc_dwi.nii.gz
suffix = 

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/mrtrix.py", line 121, in _run_interface
    convert_run = convert.run()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 829, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 760, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
mrconvert -grad /nashome3/aaa/Desktop/bids/derivatives/qsiprep/sub-005/dwi/sub-005_space-T1w_desc-preproc_dwi.b /nashome3/aaa/Desktop/bids/derivatives/qsiprep/sub-005/dwi/sub-005_space-T1w_desc-preproc_dwi.nii.gz /nashome3/aaa/Desktop/work/qsirecon_wf/sub-005_mrtrix_singleshell_ss3t/recon_wf/ss3t_csd/_dwi_file_..nashome3..aaa..Desktop..bids..derivatives..qsiprep..sub-005..dwi..sub-005_space-T1w_desc-preproc_dwi.nii.gz/create_mif/sub-005_space-T1w_desc-preproc_dwi.mif
Standard output:

Standard error:
mrconvert: [  0%] uncompressing image "/nashome3/aaa/Desktop/bids/derivatives/qsiprep/sub-005/dwi/sub-005_space-T1w_desc-preproc_dwi.nii.gz"... [0K
mrconvert: [  1%] uncompressing image "/nashome3/aaa/Desktop/bids/derivatives/qsiprep/sub-005/dwi/sub-005_space-T1w_desc-preproc_dwi.nii.gz"... [0K
.
.
mrconvert: [100%] uncompressing image "/nashome3/aaa/Desktop/bids/derivatives/qsiprep/sub-005/dwi/sub-005_space-T1w_desc-preproc_dwi.nii.gz"[0K

mrconvert: [  0%] copying from "/nashome3/...T1w_desc-preproc_dwi.nii.gz" to "/nashome3/...ce-T1w_desc-preproc_dwi.mif"... [0K
mrconvert: [  1%] copying from "/nashome3/...T1w_desc-preproc_dwi.nii.gz" to "/nashome3/...ce-T1w_desc-preproc_dwi.mif"... [0K
.
.
mrconvert: [100%] copying from "/nashome3/...T1w_desc-preproc_dwi.nii.gz" to "/nashome3/...ce-T1w_desc-preproc_dwi.mif"[0K
mrconvert: [01;31m[ERROR] error writing back contents of file "/nashome3/aaa/Desktop/work/qsirecon_wf/sub-005_mrtrix_singleshell_ss3t/recon_wf/ss3t_csd/_dwi_file_..nashome3..aaa..Desktop..bids..derivatives..qsiprep..sub-005..dwi..sub-005_space-T1w_desc-preproc_dwi.nii.gz/create_mif/sub-005_space-T1w_desc-preproc_dwi.mif": Success[0m
Return code: 1
```

**Comment by mattcieslak** [comment]
Hello, It looks like maybe the destination it's writing to isn't writable. You may need to [bind directories](https://sylabs.io/guides/3.6/user-guide/bind_paths_and_mounts.html?highlight=bind%20paths#bind-paths-and-mounts) for singularity to be able to write to them

**Comment by IRuotsa** [comment]
Thank you so much for the response. Binding solved the problem.
