### ISSUE TITLE
Error running qsiprep with singularity: AttributeError: 'NoneType' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by akhanf** [PennBBL/qsiprep#62]
Really great job on the app really look forward to trying it out!
However I'm having an issue getting it going with our existing singularity set-up, have you seen this error before?

```
[akhanf@gra603 test_qsiprep]$ singularity run -e -B /project:/project -B /scratch:/scratch -B /localscratch:/localscratch /project/6007967/akhanf/singularity/bids-apps/pennbbl_qsiprep_0.6.4.sif --bids-dir /home/akhanf/cfmm-bids/Khan/TestDatasets/dwi_multishell_blipped/ --output-dir test_out --analysis-level participant --fs-license-file /project/6007967/akhanf/opt/freesurfer/.license
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
	1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

	Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.


        Summary:                  Available Tasks:        Available Modalities:
        11 Files, 314.66MB                                T1w
        1 - Subject                                       dwi
        1 - Session


	If you have any questions, please post on https://neurostars.org/tags/bids.

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 671, in build_qsiprep_workflow
    work_dir = opts.work_dir.resolve()
AttributeError: 'NoneType' object has no attribute 'resolve'
```

**Comment by mattcieslak** [comment]
Hi @akhanf! Thanks for opening an issue for this. Can you try (assuming you want data to persist on /project and /home is auto-mounted by singularity)

```
singularity run -e -B /project:/project \
    -B /scratch:/scratch \
    -B /localscratch:/localscratch \
    -B /tmp:/tmp \
    /project/6007967/akhanf/singularity/bids-apps/pennbbl_qsiprep_0.6.4.sif \
    --bids-dir /home/akhanf/cfmm-bids/Khan/TestDatasets/dwi_multishell_blipped/ \
    --output-dir /project/test_out \
    --analysis-level participant \
    -w /project/test_work \
    --fs-license-file /project/6007967/akhanf/opt/freesurfer/.license
```

You can also `pip install qsiprep-container` and then run `qsiprep-singularity --image /project/6007967/akhanf/singularity/bids-apps/pennbbl_qsiprep_0.6.4.sif ...` and not worry about binding directories

**Comment by akhanf** [comment]
Thanks Matt! Specifying the `-w` option got me over that hump.. 

But I am now getting an error: 
```

191106-15:24:48,875 nipype.workflow IMPORTANT:

    Running qsiprep version 0.6.4:
      * BIDS dataset path: /project/6007967/akhanf/cfmm-bids/data/Khan/TestDatasets/dwi_singleshell.
      * Participant list: ['001'].
      * Run identifier: 20191106-152448_1ed6b1a4-739e-4840-af91-bbb8ea7bba26.

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 839, in build_qsiprep_workflow
    force_syn=opts.force_syn
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 241, in init_qsiprep_wf
    force_syn=force_syn)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 507, in init_single_subject_wf
    num_t1w=len(subject_data['t1w']))
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/anatomical.py", line 273, in init_anat_preproc_wf
    template_image=ref_img)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/anatomical.py", line 923, in init_output_grid_wf
    resample_to_voxel_size.inputs.voxel_size = (voxel_size, voxel_size, voxel_size)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'voxel_size' trait of a ResampleInputSpec instance must be a tuple of the form: (a float, a float, a float), but a value of (None, None, None) <class 'tuple'> was specified.
```
which seems to persist even when I try a completely different dataset?

**Comment by mattcieslak** [comment]
This is due to a missing `--output-resolution` argument. You need to specify the size of the voxels in your preprocessed data. This needs a better error message (eg #36, #37). You can specify a smaller size than the input data if you want your output to be upsampled

**Comment by akhanf** [comment]
Super, I'm off to the races now! Sorry for not checking those issues first!
