### ISSUE TITLE
nibabel error

### ISSUE THREAD

**Issue by araikes** [PennBBL/qsiprep#78]
Hi @mattcieslak,
I pulled `qsiprep:0.6.5` this morning and proceeded to run it on a dataset that successfully completed for most people (same dataset from #74 with 5 people having the N4 issue). For everyone so far, I get this error: 

```
Node: qsiprep_wf.single_subject_omega002_wf.dwi_preproc_ses_bline_dir_AP_run_001_wf.hmc_sdc_wf.prepare_rpe_b0
Working directory: /data/omega/derivatives/qsiprep-0.6.5/baseline_2mm-iso_dedicated-fmap/scratch/qsiprep_wf/single_subject_omega002_wf/dwi_preproc_ses_bline_dir_AP_run_001_wf/hmc_sdc_wf/prepare_rpe_b0

Node inputs:

b0_file = ['/nifti/sub-omega002/ses-bline/fmap/sub-omega002_ses-bline_dir-PA_run-001_epi.nii.gz']
b0_threshold = 100
max_num_b0s = 3
orientation = LAS
output_3d_images = False

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/fmap.py", line 79, in _run_interface
    merged_b0s = concat_imgs(b0_fieldmap_imagedata, auto_resample=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 428, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 268, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 428, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 268, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 428, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 268, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 428, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 271, in check_niimg
    niimg = load_niimg(niimg, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg.py", line 114, in load_niimg
    + short_repr(niimg))
TypeError: Data given cannot be loaded because it is not compatible with nibabel format:
0.0
```

Docker call is below:
```
docker run -i --rm -v /data/omega/nifti:/nifti:ro -v /data/omega/derivatives/qsiprep-0.6.5/baseline_2mm-iso_dedicated-fmap:/data/omega/derivatives/qsiprep-0.6.5/baseline_2mm-iso_dedicated-fmap -v /data/BL2/BIDS_derivatives/code/license.txt:/opt/freesurfer/license.txt pennbbl/qsiprep:0.6.5 /nifti /data/omega/derivatives/qsiprep-0.6.5/baseline_2mm-iso_dedicated-fmap participant --participant-label omega002 -w /data/omega/derivatives/qsiprep-0.6.5/baseline_2mm-iso_dedicated-fmap/scratch --omp-nthreads 8 --nthreads 12 --mem_mb 30000 --output-space T1w --output-resolution 2 --prefer-dedicated-fmap --use-syn --b0-to-t1w-transform Affine --hmc-model eddy --force-spatial-normalization
```
Anything else you would need to diagnose the issue?

**Comment by mattcieslak** [comment]
Would you be able to send a copy of '/nifti/sub-omega002/ses-bline/fmap/sub-omega002_ses-bline_dir-PA_run-001_epi.nii.gz' ?

**Comment by mattcieslak** [comment]
I can replicate this locally. Should be fixed soon
